### ISSUE TITLE
Issue Sending images taken to a server

### ISSUE THREAD

**Issue by jriack** [ArduCAM/ArduCAM_ESP32S_UNO#18]
I'm currently trying to take images with the arducam and send these images to a database stored on a server. I'm sending the image as a string of the base64 encoded bits from reading the SPI, and after testing it seems like all the data is coming out correct, but when I try to decode the image it produces an invalid jpeg. I was wondering if there are any special formatting things I need to do with the data read from the SPI transfer to properly save the image taken as a JPEG.

**Comment by ArducamSupport** [comment]
Hi,
The data read from FIFO is not all jpeg image data, you have to filter the jpeg image's head and tail and save the data from head to tail.

**Comment by jriack** [comment]
Thank you I was able to solve the issue!
