### ISSUE TITLE
ArduCAM ESP32 Series Development Boards - documentation and distributors

### ISSUE THREAD

**Issue by chrwick** [ArduCAM/ArduCAM_ESP32S_UNO#3]
Hi!

I have searched the web, but I did not find anything about these boards.
Where can I find the documentation? Where can I buy those?

**Comment by ArduCAM** [comment]
We will release it next week, you can find the user guide here:
www.arducam.com/downloads/ESP32_UNO/ArduCAM_ESP32_UNO_DS.pdf

**Comment by chrwick** [comment]
Ok, thanks for the quick reply.
Will it be available through the distributors immediately?

**Comment by ArduCAM** [comment]
Where are you from? In US, you can order from Amazon now. Or else you have to order from us.

**Comment by chrwick** [comment]
Germany/Europe

**Comment by ArduCAM** [comment]
Please send email to us admin at arducam dot com

**Comment by chrwick** [comment]
Received the ESP32 board. Thanks!
Closing issue.
